### ISSUE TITLE
Needs to be completed

### ISSUE THREAD

**Issue by aviflombaum** [learn-co-curriculum/ttt-game-status#1]
Outline https://github.com/learn-co-curriculum/ttt-game-status/blob/master/README.md

Deadline- 9/10/15

**Comment by aviflombaum** [comment]
Done, review @AnnJohn please. @deniznida or @ipc103 :eyes: maybe?

**Comment by AnnJohn** [comment]
Assigned to @ipc103 for review

Deadline: today, 9/17/15

**Comment by ipc103** [comment]
added helper method description 

diff: https://github.com/learn-co-curriculum/ttt-game-status/commit/7a056e475ca959ae7538b3b7f3df47b25a6ce1e8

**Comment by aviflombaum** [comment]
Thanks @ipc103 it's good. @AnnJohn this can be marked as done.
