### ISSUE TITLE
Wrong use of variable assignment 

### ISSUE THREAD

**Issue by rkoeze** [learn-co-curriculum/ttt-game-status#11]
![screen shot 2016-03-01 at 4 31 37 pm](https://cloud.githubusercontent.com/assets/7535628/13446776/1b12285e-dfcb-11e5-84cc-bae2ac26677c.png)

See attached picture. Should highlighted use "==" instead?

**Comment by AnnJohn** [comment]
thanks @rkoeze; we updated the readme.
