### ISSUE TITLE
Intro to Ruby ~ Directions don't correspond to specs

### ISSUE THREAD

**Issue by alexcrisan** [learn-co-curriculum/ttt-game-status#15]
Hi, 

I am on the Tic Tac Toe Game Status project and I noticed that it says this for the #full method:

"The #full? method doesn't need to worry about draws or winning combinations, simply return false if there is an available position and true if there is not."

But when I run learn, I get a failure that states:
"#full?
returns true for a draw (FAILED - 1)" 

Can you please verify this as it is causing me, and I'm assuming others, some confusion. 

Thank you,

Alex

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!

**Comment by gj** [comment]
Hi @alexcrisan,

I can understand your confusion, but that RSpec test is correct as-written. The `#full?` method _should_ return `true` for a drawn game; that is, a game in which neither player has won and the `board` has no open spaces left.

Your `#full?` method should also return true for a `board` full of `X` tokens, a `board` full of `Y` tokens, or any combination thereof. In fact, your `#full?` method doesn't even need to know the rules of Tic-Tac-Toe or even know that it's being called in a game of Tic-Tac-Toe. All it cares about is whether the `board` array passed to it contains at least one blank space.

Hope that clears it up a bit!

**Comment by AnnJohn** [comment]
thank you @ga-be!
