### ISSUE TITLE
test for #over? not specific enough

### ISSUE THREAD

**Issue by yakovkiff** [learn-co-curriculum/ttt-game-status#22]
Hi, the test for #over? doesn't require that the method returns true for a winning but incomplete board.  The way the tests currently have it, #over? is effectively synonymous with #full?  And in fact, the following code passed the test.  

def over?(board)
  full?(board)
end

Presumably the test for #over? should include the case of a winning but incomplete board?

**Comment by gj** [comment]
Fixed in 2f5bf5e. Thanks @yakovkiff !
