### ISSUE TITLE
Win Constant won't pass if the array indexes aren't in a specific order

### ISSUE THREAD

**Issue by AnnJohn** [learn-co-curriculum/ttt-game-status#3]
For example, test will pass if the array indexes are in the order below 

![screen shot 2015-09-29 at 11 23 49 am](https://cloud.githubusercontent.com/assets/1892150/10168892/b4881294-669c-11e5-91be-6db4b56f477b.png)

But will not pass if I change the order of the last array, seen below:

![screen shot 2015-09-29 at 11 25 46 am](https://cloud.githubusercontent.com/assets/1892150/10168964/f753e9ae-669c-11e5-9019-88aa61924866.png)

Not sure how to change the tests to allow for any order to pass. To make it easier you can change the tests so that the last array needs [2,4,6]  to make the tests pass and then in the readme let students know that when they create this constant, they should order their indexes in the arrays in ascending order.

**Comment by aviflombaum** [comment]
addressed with custom rspec matcher `include_array` defined in 18c08c5
